### ISSUE TITLE
Could not multiply by non-number

### ISSUE THREAD

**Issue by HRItdy** [enyen/KOVIS_VisualServo#2]
Hi Enyen,

Thanks for sharing the code! I have trained a kovis1 model and use the command `rob.servo('pick_tube', 10, [0.01, 0.01, 0.01, 0.05, 0, 0], [0.1, 5])` to test it.
I printed the velocity and orientaion:
``` 
Velocity: [tensor(0.0022), tensor(0.0024), tensor(0.0024), tensor(-3.7409e-06), 0, 0]
Orientation: <Orientation: RV(-1.086, -0.000, -0.000)>
```

Are they reasonable? Then an error raised:
```
Traceback (most recent call last):
  File "/home/lab_cheem/miniforge3/envs/kovis1-2.7/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/lab_cheem/miniforge3/envs/kovis1-2.7/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lab_cheem/catkin_ws/src/WP2/kovis1/inference_oja.py", line 204, in _watch_servo
    self.rob.speedl_tool(vec, ACCE, t)
  File "/home/lab_cheem/.local/lib/python3.8/site-packages/urx/robot.py", line 176, in speedl_tool
    v = pose.orient * m3d.Vector(velocities[:3])
  File "/home/lab_cheem/.local/lib/python3.8/site-packages/math3d/vector.py", line 455, in __rmul__
    raise utils.Error('__rmul__ : Could not multiply by non-number')
math3d.utils.Error: __rmul__ : Could not multiply by non-number
```

This seems to be an internal issue in python urx. I searched this but found no solution. Did you encounter this problem before? Any suggestion is appreciated. Thanks!

Regards,
Daiying

**Comment by enyen** [comment]
indeed it seems to be an issue with urx and math3d. 
Maybe you could try to revert math3d to an earlier version https://gitlab.com/morlin/pymath3d/-/tags

**Comment by HRItdy** [comment]
Thanks for your reply.

I tried all the other versions of math3d and kept getting this issue:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lab_cheem/catkin_ws/src/WP2/kovis1/inference_oja.py", line 161, in servo
    self.move_tcp_perpendicular()
  File "/home/lab_cheem/catkin_ws/src/WP2/kovis1/inference_oja.py", line 95, in move_tcp_perpendicular
    tcp_pose = self.rob.getl()
  File "/home/lab_cheem/.local/lib/python3.8/site-packages/urx/robot.py", line 220, in getl
    return t.pose_vector.get_array().tolist()
AttributeError: 'numpy.ndarray' object has no attribute 'get_array'
```
It seems to be the issue of the numpy? I revert the numpy version but still get this. Do you remember the configuration you used before? Thanks!

**Comment by HRItdy** [comment]
Never mind Enyen, I found the original urx code is different with this. 
`        return t.pose_vector.tolist()`

I will reinstall the urx. Thanks!

**Comment by HRItdy** [comment]
Hi Enyen,

For now when I run the servo script, the robot will automatically transform to the position as shown below:
![eff2cd4aa0091a48183af17f0d08801](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/1ac04040-6a80-4646-b5a0-b2e08cd64d58)

I changed the position of the object in pybullet but the gripper still aims at the ground. Regarding in the final demo the gripper should to be horizontal, should I change the urdf to make the gripper be horizontal? Or there is some other easier way to achieve this? And if we need to update the position of the robot in the script, or it will be automatically updated according to the training dataset? Thanks!

**Comment by enyen** [comment]
https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/inference_oja.py#L158
The code `move_tcp_perpendicular` everytime before running the servo, so you could modify this line according to your application.

**Comment by PrithvirajRay** [comment]
Hi Enyen, thanks for the response, however this is at the inference stage right? Wouldnt we want to train the robot in that horizontal end position from the training data generation phase itself? Basically we want the robot to grab the tube horizontally so in the simulator during training data generation also we need the robot to move that similar way right?

**Comment by HRItdy** [comment]
Hi Enyen,

I generated 7000 records to train the model, and the result seems not good enough.
In some test image, the distribution of the keypoints should be good (but several kps fall into the background):
![0046_0 49_0 69](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/9b718c17-63f3-413b-8e23-ac8e694147bb)

But in some other images, the distribution is not good, and the object is not completely segmented out:
![0041_0 50_0 69](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/4678f1fd-a95a-4a2e-b50c-74f1e2a7ff1c)
![0040_0 00_0 69](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/b9e595a2-f66e-459c-9275-fc3e0f5d4767)

And this is the final loss. I guess it's not good enough:
![Screenshot from 2024-05-08 20-39-25](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/a3d21fc0-a0eb-4ea7-9173-92224d88bf17)

Is there any suggestion to improve the performance of the model? Is this because the object is too small?
Thanks!

**Comment by HRItdy** [comment]
Hi Enyen,

I have sent out the meeting link through gmail. Pls let me know if you didn't receive this. 

By the way, is there by any change you encountered ```no realsense device can be detected``` issue? It seems due to the driver. Is it okay if we directly reinstall the driver? Will this destroy some features you made before? Thanks!

**Comment by enyen** [comment]
> Hi Enyen, thanks for the response, however this is at the inference stage right? Wouldnt we want to train the robot in that horizontal end position from the training data generation phase itself? Basically we want the robot to grab the tube horizontally so in the simulator during training data generation also we need the robot to move that similar way right?

For data generation, you have to design your task in data cfg yaml according to your application.
For inference, place the gripper accordingly ie. horizontally in your case.



> Hi Enyen,
> 
> I generated 7000 records to train the model, and the result seems not good enough. In some test image, the distribution of the keypoints should be good (but several kps fall into the background): ![0046_0 49_0 69](https://private-user-images.githubusercontent.com/139546856/328906718-9b718c17-63f3-413b-8e23-ac8e694147bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzcxMTksIm5iZiI6MTcxNTI3NjgxOSwicGF0aCI6Ii8xMzk1NDY4NTYvMzI4OTA2NzE4LTliNzE4YzE3LTYzZjMtNDEzYi04ZTIzLWFjOGU2OTQxNDdiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNzQ2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2NmNDIxMmZkNGNlYjRjMGM4N2NiMDg1YTQzODJjNjI1MTU5Mjk2MzRmNTI5ZGQ5MTg1YjIzY2FjMWYyNTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._96sE_1NBrK494C26hUA7IbM6iy2pRwq44NlyWfi03Y)
> 
> But in some other images, the distribution is not good, and the object is not completely segmented out: ![0041_0 50_0 69](https://private-user-images.githubusercontent.com/139546856/328906797-4678f1fd-a95a-4a2e-b50c-74f1e2a7ff1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzcxMTksIm5iZiI6MTcxNTI3NjgxOSwicGF0aCI6Ii8xMzk1NDY4NTYvMzI4OTA2Nzk3LTQ2NzhmMWZkLWE5NWEtNGEyZS1iNTBjLTc0ZjFlMmE3ZmYxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNzQ2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzA2YWQ1MzIzZWRlMGI2ZGY5ODliOWJmNzFlZTFkZTcxYmJjZmEzMGI4MGQ2NTAzNDVjMzYwNTI1MjE0M2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KmzD4QqvL_TXc4mvLXX81SvZb3wAEaN77kfHxQEAS2E) ![0040_0 00_0 69](https://private-user-images.githubusercontent.com/139546856/328906852-b9e595a2-f66e-459c-9275-fc3e0f5d4767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzcxMTksIm5iZiI6MTcxNTI3NjgxOSwicGF0aCI6Ii8xMzk1NDY4NTYvMzI4OTA2ODUyLWI5ZTU5NWEyLWY2NmUtNDU5Yy05Mjc1LWZjM2UwZjVkNDc2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNzQ2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjgzMjdiZDFhZjhmM2ZiMTc3OWI5NTM5YzYxNzMyYjRiMGU5MjA4ODc4ZDhkZDhhYTFjZTZhOTNkZGU4OTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wMzWrZoCsZYMf-pNQ5YCF2lbGcg4MZS4-HNEBV5E7zQ)
> 
> And this is the final loss. I guess it's not good enough: ![Screenshot from 2024-05-08 20-39-25](https://private-user-images.githubusercontent.com/139546856/328906930-a3d21fc0-a0eb-4ea7-9173-92224d88bf17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzcxMTksIm5iZiI6MTcxNTI3NjgxOSwicGF0aCI6Ii8xMzk1NDY4NTYvMzI4OTA2OTMwLWEzZDIxZmMwLWEwZWItNGVhNy05MTczLTkyMjI0ZDg4YmYxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNzQ2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWRkYmY2ZGNkNWYwMWQ1MTMyY2RkMDc2ZTI5MGRjODRhNjIyYzM1MmE1MzI2MDJlMmE0MDJkMDAwYTFjOTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kuUpoHGBvrcWxAAL6j4ylxk-JUL9AdKmpc7MvClZ4jQ)
> 
> Is there any suggestion to improve the performance of the model? Is this because the object is too small? Thanks!

If the training data is generated correctly, try to tune the hyperparams in the training cfg yaml.
Maybe using a plain background for debugging.




> Hi Enyen,
> 
> I have sent out the meeting link through gmail. Pls let me know if you didn't receive this.
> 
> By the way, is there by any change you encountered `no realsense device can be detected` issue? It seems due to the driver. Is it okay if we directly reinstall the driver? Will this destroy some features you made before? Thanks!

Mostly connection issues for me. 
But reinstalling the driver should be fine.

**Comment by HRItdy** [comment]
Hi Enyen,

Really thanks for your help! I move the object closer to the arm. But after doing this, the base is included into the view. Does this matter?
![image](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/5658b6f8-e85e-4e7f-9f3f-7f1b76278dbc)

And in this setting the arm also seems to be a little extreme. Should I move it away further? And this may cause the object to fall on the edge of the base, does this matter? Really appreciate your help!

Regards,
Daiying

**Comment by HRItdy** [comment]
Move away further will result this:

![MicrosoftTeams-image (36)](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/357feaae-323a-4ced-a356-5b10f9113fe9)

The object will fall on the edge of the base. Does this matter? Thanks!

**Comment by enyen** [comment]
use `cam_clip` to limit camera range and avoid seeing robot base https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/cfg/dataset_insert_plug.yaml#L34

**Comment by HRItdy** [comment]
Thanks for your reply Enyen!
Based on your suggestion, I tried to paste the image on a plain background:
![Screenshot from 2024-05-11 20-10-38](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/b8715cca-070d-48d7-a07f-92f66342cfa3)

This is the saved training image:
![train](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/8056011a-7c22-499f-97dd-14ee8c32df3a)

And this is the loss, seems still very high, I will adjust the hyperparameters to reduce it
![Screenshot from 2024-05-11 20-36-51](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/9588fa43-69da-4934-bc8d-ba424cccbe97)

Is there any obvious issue in this procedure now? In addition, now there is random noise on the image. Should I also disable the noise for now? 
![0005_0 00_0 69](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/6b86f3a1-42bb-42a5-b345-dbe9cc77d4ff)

Thanks!

**Comment by HRItdy** [comment]
Hi Enyen,

I reduced the number of keypoints to 6 and adjust ```concentrate``` to -30 and ```inside``` to 60. Now there are 2 kps falling into the object and move with it:
![0330_0 09_0 66](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/0bee527d-16bc-4491-8b15-558d51fdf0c6)
![0331_0 00_0 66](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/ce0f4c17-e2ce-457a-a9cb-7b49948085aa)
![0332_0 02_0 70](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/91100940-2aaa-4423-a997-30881081256e)
![0333_0 03_0 68](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/5d1235f4-606f-4677-a63d-42308f847261)
![0343_0 09_0 68](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/700fccca-e339-4e08-88c5-bddef4c018c1)
![0344_0 15_0 68](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/c6697aa7-4bd1-4094-ae84-3ffbe31c95f6)
![0345_0 10_0 67](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/02ff331f-b4b6-481f-93f4-988d23fde760)
![0346_0 00_0 67](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/aa698d10-4550-42b9-bc1d-d9c721ac08cc)
But the loss still seems not good enough:
![Screenshot from 2024-05-12 16-24-42](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/7a85d936-0f97-43ea-8f80-4aa5c25688b4)

I would like to ask what's the reasonable range of the loss? Should I add the background back now and retrain the model, or continue to adjust the parameters to reduce the loss? Thanks!

**Comment by enyen** [comment]
The speed loss does not look good. 
Is the training data generated correctly? You can check by verifying the poses in first step of all episodes are correct.

Yes, you should continue to try different settings and also on robot.

**Comment by HRItdy** [comment]
Thanks for your reply Enyen!

I sampled several initial steps: 
![00001_00](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/e5bdba58-034f-4725-aa20-3c924155ee9c)
![00002_00](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/c09de125-c7fb-41e4-bbf8-12fb47bf03f7)
![00000_00](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/864a96e8-5413-4a50-9e64-ceaa656f6b2a)

They have the similar relative positions (but has some random orientation). Is this correct?

And I noticed that in one episode, seems like the camera has some translation in different steps:

![00002_00](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/6bb3c876-aac9-4ce3-ab90-4ed37b26da6e)
![00002_01](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/797bf8a5-1015-4e1b-8778-9eba913fb265)
![00002_02](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/8c2f0570-5e7e-4396-94fc-e8bf7c0430c8)
![00002_03](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/57332455-fd65-42eb-8f13-3490864765ca)
![00002_04](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/16a2575a-e795-4022-9ae0-49c7bd0525fe)

Should the camera be fixed in one episode? Is this the reason why the speed loss is not good enough?

Thanks!

**Comment by enyen** [comment]
yes, camera pose is randomized in every images.
You can turn it off at https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/cfg/dataset_insert_plug.yaml#L33

**Comment by HRItdy** [comment]
Thanks Enyen!

I increased the dataset size and adjusted the parameters, the result is shown as follows:
![Screenshot from 2024-05-15 12-16-50](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/80bd2cf1-70b4-4486-a590-ea2351ebb005)

Is this loss good enough? Should the ideal speed loss be smaller than 0.1? Thanks!

**Comment by HRItdy** [comment]
Hi Enyen, please forget the problem. I tested this model on the real robot, and the performance is good (although bad performance from some specific initial positions, I will continue to adjust the hyperparameter to improve this). Really thanks for your help!

**Comment by HRItdy** [comment]
Hi Enyen,

Sorry for the bother, I'm trying to understand the code, and visualize the keypoints in the inference phase. I found there seems to be some inconsistency between the inference and training phases.

In the training, the `inference` is set to be False
https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/train_model.py#L8
So the encoder will take one single image as input:
https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/train_servo.py#L77

But in the inference phase, parameter `inference` is set to be True, so it will require images from left and right camera simultaneously:
https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/inference_oja.py#L132

And when I change it to False, the output keypoints have one dimension all 0:
![image](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/06abad88-5b01-4ce8-a760-f3a575cc6953)
If I keep the `inference` as True and input the right and left images simultaneously like:
```
kp = getattr(self, 'kp_{}'.format(action))([infraL.cuda(), infraR.cuda()])
```
the output keypoints only have one dimension:
![image](https://github.com/enyen/KOVIS_VisualServo/assets/139546856/528e3c26-479a-4d3b-a669-aa723b81365a)

I would like to ask whether `inference` should be True. If so how to use this one dimension vector to visualize the keypoints. Thanks! Sorry for any bother!

**Comment by enyen** [comment]
When `inference=True`, keypoints from left and right images are concatenated:
https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/train_model.py#L69

You can seperate the `enc` and `cvt` in `init_network()`:
```diff
- setattr(self, 'net_servo_{}'.format(net), torch.nn.Sequential(enc, cvt))
+ setattr(self, 'net_enc_{}'.format(net), enc)
+ setattr(self, 'net_cvt_{}'.format(net), cvt)

- getattr(self, 'net_servo_{}'.format(net)).eval()
+ getattr(self, 'net_enc_{}'.format(net)).eval()
+ getattr(self, 'net_cvt_{}'.format(net)).eval()
```

In `_watch_servo()`:
```diff
- vec, speed = getattr(self, 'net_servo_{}'.format(action))([infraL.cuda(), infraR.cuda()])
+ kps = getattr(self, 'net_enc_{}'.format(action))([infraL.cuda(), infraR.cuda()])
+ vec, speed = getattr(self, 'net_cvt_{}'.format(action))(kps)
+ kpl, kpr = kps.squeeze().chunk(chunks=2, dim=1)
+ vis_kp(kpl, kpr)  # todo
```

Keypoints are flatten:
https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/train_model.py#L131
into `[h1, w1, m1, ..., hK, wK, mK]`

**Comment by HRItdy** [comment]
Really thanks for your reply! Yes the output is the result after I separated the `enc` and `cvt`. Sorry I have one more question about the output. What do `h, w, m` represent? In the paper the output of the keypointer is a 32*32 feature map with K channels, but in the code the output is simplified to the coordination of keypoints `hi, wi`. Do I understand correctly? Thanks!

**Comment by enyen** [comment]
`h` and `w` make up a points at the first and second axis of the 2D feature map; `m` is the magnitude or intensity of the point.
https://github.com/enyen/KOVIS_VisualServo/blob/5ea1d9abe1a6c9c99fb3c2046e16251d9e57b10f/train_model.py#L114
